spring.profiles.active=integration_test

spring.application.name=casinowallet

spring.jackson.time-zone=UTC

spring.main.allow-circular-references=true

jwt.secret=secret-valid-only-for-tests@#$*&y123876

access.expiration=1800
